### ISSUE TITLE
Service Catalog

### ISSUE THREAD

**Issue by Favenzio** [fsulib/website-refresh-issues#2]
This feature of the website is a view that works with published Services (Content Type) It allows searching and filtering by category. https://www.lib.fsu.edu/service-catalog

**Comment by jessicapple** [comment]
How do we manage redirecting service pages that have limited information, but also those that include redirects from the service menu? ex: https://www.lib.fsu.edu/service/data-management 

https://www.lib.fsu.edu/service/research-data-services

**Comment by rkmase** [comment]
Not needed in Refresh
