### ISSUE TITLE
Special Collections: Redirects

### ISSUE THREAD

**Issue by rkmase** [fsulib/website-refresh-issues#56]
SC needs redirects for following pages:

- SCA main page[ https://www.lib.fsu.edu/sca](https://www.lib.fsu.edu/sca)
- Heritage main page[ https://www.lib.fsu.edu/sca/heritage-and-university-archives](https://www.lib.fsu.edu/sca/heritage-and-university-archives)
- Heritage museum page[ https://www.lib.fsu.edu/sca/heritage-and-university-archives/heritage-museum](https://www.lib.fsu.edu/sca/heritage-and-university-archives/heritage-museum)
- Registration Form[ https://www.lib.fsu.edu/form/special-collections-appointment-request-form](https://www.lib.fsu.edu/form/special-collections-appointment-request-form)
- Class Visit Request Form[ https://www.lib.fsu.edu/form/sca/class-visit-request](https://www.lib.fsu.edu/form/sca/class-visit-request)

**Comment by Favenzio** [comment]
These redirects have been created.
