### ISSUE TITLE
"Save" Changed Content 

### ISSUE THREAD

**Issue by jessicapple** [fsulib/website-refresh-issues#61]
When clicking "Save" it doesn't actually confirm you are saved and content editors might be confused by this.

**Comment by barsenault-fsu** [comment]
Clicking save puts a message at the top of the page in the default message area when the user clicks the Save button:

![image](https://github.com/fsulib/website-refresh-issues/assets/54671134/4a581783-1aab-43af-a68a-97e0000161b4)
