### ISSUE TITLE
Text Component and Image browsing issues

### ISSUE THREAD

**Issue by jessicapple** [fsulib/website-refresh-issues#69]
Text components don't allow for browsing of already uploaded images, only uploading of new images. We attempted to add an existing image and it appears to be breaking.  Example seen on https://test.lib.fsu.edu/node/3218

<img width="1122" alt="Screen Shot 2023-01-21 at 6 28 19 PM" src="https://user-images.githubusercontent.com/87393268/213894045-4e2e9698-d17b-448b-9684-cce3c16f4e64.png">

**Comment by barsenault-fsu** [comment]
This appears to be fixed now.  Image browsing has been removed from CKeditor and a Media field has been added to the Text Component
